### ISSUE TITLE
md的预览窗口关闭后，无法立即重新打开预览窗口

### ISSUE THREAD

**Issue by shiyingyan** [vv13/markdown-auto-preview#1]
1. 如果只打开一个md文件的情况，无法再自动重新打开预览窗口
2. 如果同时有其它文件打开，则需要切换到其它文件标签再切回来，才可以再重新自动打开预览窗口
3. 如果同时打开的其它文件，不是md，则标签切换回来时，仍然无法自动重新打开预览窗口

![image](https://github.com/vv13/markdown-auto-preview/assets/8131314/ffcab0a7-cb01-4b59-af24-f4a04ada7ac1)

**Comment by vv13** [comment]
1. 手动关闭后，可使用内置命令重新打开，比如Cmd+Shift+v或 Cmd K + V。
2.符合预期。
3. v0.3.3 已经修复了该问题。

**Comment by shiyingyan** [comment]
写的已经很不错了。 但总感觉还不够自动。  只有一个文件打开时，能不能点击标签，也重新打开文件呢

**Comment by vv13** [comment]
> 写的已经很不错了。 但总感觉还不够自动。 只有一个文件打开时，能不能点击标签，也重新打开文件呢

能再具体点么？ 没明白你的需求
