### ISSUE TITLE
Add option to Auto Close Preview when switching focused tab away from the markdown file

### ISSUE THREAD

**Issue by dcalatayud** [vv13/markdown-auto-preview#2]
It would be quite convenient if there was an option to automatically close the Preview when you switch the focused tab away from a Markdown file in VSCode. The workflow would be as follows: You start coding, then open a Markdown (MD) file, which triggers the Preview window to open on the right side. When you switch back to your previous coding tab, the Preview window would automatically close.

**Comment by vv13** [comment]
Good advice! Now, you can try setting markdown-auto-preview.autoClosePreviewAfterSwitch to enable this feature:
![markdown-auto-preview](https://github.com/vv13/markdown-auto-preview/assets/9440756/b3109932-3405-45d9-b774-603164cd91d8)

**Comment by dcalatayud** [comment]
Thanks for the quick implementation @vv13!!! 
However, I've noticed that it doesn't seem to work when switching from a Markdown file to a .ipynb Jupyter notebook (which is my main workflow). I've attached a GIF demonstrating the issue. Is this a limitation, or does it require extra handling for notebooks?
![Animation](https://github.com/vv13/markdown-auto-preview/assets/119454383/027af180-eda7-4b4f-b893-b5e9abcaa1f5)

**Comment by vv13** [comment]
> Thanks for the quick implementation @vv13!!! However, I've noticed that it doesn't seem to work when switching from a Markdown file to a .ipynb Jupyter notebook (which is my main workflow). I've attached a GIF demonstrating the issue. Is this a limitation, or does it require extra handling for notebooks? ![Animation](https://private-user-images.githubusercontent.com/119454383/309561891-027af180-eda7-4b4f-b893-b5e9abcaa1f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc4MTQsIm5iZiI6MTcwOTYzNzUxNCwicGF0aCI6Ii8xMTk0NTQzODMvMzA5NTYxODkxLTAyN2FmMTgwLWVkYTctNGI0Zi1iODkzLWI1ZTlhYmNhYTFmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRiMmI2YWNhODgxMjFmYzQwZjZhNTg4NjQ1ZjM4NzdiMzc3MjQwNDVjNmM3ZTlmOTRjOTU3M2ZjZTlhYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wkin1DbJ0FSYkx5DyaMluNRMCEpr3LtNKyWRs0riZTE) [ ![Animation](https://private-user-images.githubusercontent.com/119454383/309561891-027af180-eda7-4b4f-b893-b5e9abcaa1f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc4MTQsIm5iZiI6MTcwOTYzNzUxNCwicGF0aCI6Ii8xMTk0NTQzODMvMzA5NTYxODkxLTAyN2FmMTgwLWVkYTctNGI0Zi1iODkzLWI1ZTlhYmNhYTFmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRiMmI2YWNhODgxMjFmYzQwZjZhNTg4NjQ1ZjM4NzdiMzc3MjQwNDVjNmM3ZTlmOTRjOTU3M2ZjZTlhYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wkin1DbJ0FSYkx5DyaMluNRMCEpr3LtNKyWRs0riZTE) ](https://private-user-images.githubusercontent.com/119454383/309561891-027af180-eda7-4b4f-b893-b5e9abcaa1f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc4MTQsIm5iZiI6MTcwOTYzNzUxNCwicGF0aCI6Ii8xMTk0NTQzODMvMzA5NTYxODkxLTAyN2FmMTgwLWVkYTctNGI0Zi1iODkzLWI1ZTlhYmNhYTFmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRiMmI2YWNhODgxMjFmYzQwZjZhNTg4NjQ1ZjM4NzdiMzc3MjQwNDVjNmM3ZTlmOTRjOTU3M2ZjZTlhYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wkin1DbJ0FSYkx5DyaMluNRMCEpr3LtNKyWRs0riZTE) [ ](https://private-user-images.githubusercontent.com/119454383/309561891-027af180-eda7-4b4f-b893-b5e9abcaa1f5.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2Mzc4MTQsIm5iZiI6MTcwOTYzNzUxNCwicGF0aCI6Ii8xMTk0NTQzODMvMzA5NTYxODkxLTAyN2FmMTgwLWVkYTctNGI0Zi1iODkzLWI1ZTlhYmNhYTFmNS5naWY_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwNVQxMTE4MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mYzRiMmI2YWNhODgxMjFmYzQwZjZhNTg4NjQ1ZjM4NzdiMzc3MjQwNDVjNmM3ZTlmOTRjOTU3M2ZjZTlhYjQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wkin1DbJ0FSYkx5DyaMluNRMCEpr3LtNKyWRs0riZTE)

Sorry, I can't find a way to make everything work. There's a mechanism where .ipynb files are not treated as a TextEditor, so I can't subscribe to state changes between certain types of editor.

I'll try to solve this problem after a few days, thanks for your support.

references: 
- https://github.com/microsoft/vscode-docs/issues/3424

**Comment by dcalatayud** [comment]
Perfect, thanks!
But don't worry too much about it. Your extension is already proving to be really useful for my workflow :)
